parameters:
  oai_pmh_api:
    url: 'https://datahub.vlaamsekunstcollectie.be/oai'
    metadata_prefix: 'oai_lido'
    namespace: 'lido'
    id_prefix: 'oai:datahub.vlaamsekunstcollectie.be:mskgent.be:'
    set: 'institution:museum_voor_schone_kunsten_gent'

    max_records: 100

  datahub_fields:
    object_number: 'descriptiveMetadata/objectIdentificationWrap/repositoryWrap/repositorySet/workID[@type="object-number"]'
    title:         'descriptiveMetadata/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@pref="preferred"]'
    creator:       'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/nameActorSet/appellationValue[@pref="preferred"]'
    creator_role:  'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/roleActor/term'

  # Certificate Authority (also known as 'cacert') may not work on its own depending on your system and PHP configuration,
  # that's why a cacert.pem is included in this project (from https://curl.haxx.se/docs/caextract.html).
  # Set override_certificate_authority to 'true' when we need to specify our own cacert.pem (can be a relative path or an absolute system path).
  override_certificate_authority: true
  ssl_certificate_authority_file: 'cacert.pem'
