parameters:
  oai_pmh_api:
    url: 'https://datahub.mskgent.be/oai'
    metadata_prefix: 'oai_lido'
    namespace: 'lido'
    id_prefix: 'oai:datahub.mskgent.be:mskgent.be:'

  datahub_fields:
    Instellingsnaam NL:
      xpath: 'descriptiveMetadata/objectIdentificationWrap/repositoryWrap/repositorySet[not(@type)]/repositoryName/legalBodyName/appellationValue[@xml:lang="nl"]'
      record: S-46
    Afdeling NL:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="department"]/term'
      record: S-46
    Collectie NL:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="collection"]/term[@xml:lang="nl"]'
      record: S-46
    Collectie FR:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="collection"]/term[@xml:lang="fr"]'
      record: S-46
    Collectie EN:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="collection"]/term[@xml:lang="en"]'
      record: S-46
    Collectie externe bron:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="collection"]/conceptID[@source="AAT"]'
      record: S-46
    Huidige standplaats NL:
      xpath: 'descriptiveMetadata/objectIdentificationWrap/repositoryWrap/repositorySet[not(@type)]/repositoryLocation/namePlaceSet/appellationValue'
      record: S-66
    Naam vervaardiger NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/nameActorSet/appellationValue[@pref="preferred" and @xml:lang="nl"]'
      record: 1909-OO
    Rol vervaardiger NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/roleActor/term[@xml:lang="nl"]'
      record: 1909-OO
    Rol vervaardiger FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/roleActor/term[@xml:lang="fr"]'
      record: 1909-OO
    Rol vervaardiger EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/roleActor/term[@xml:lang="en"]'
      record: 1909-OO
    Rol vervaardiger externe bron:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/roleActor/conceptID[@source="AAT"]'
      record: 1909-OO
    Geboortedatum begin:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalDatesActor[@type="birth-date"]/earliestDate'
      record: 1874-C
    Geboortedatum eind:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalDatesActor[@type="birth-date"]/latestDate'
      record: 1874-C
    Precisie geboortedatum:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalDatesActor[@type="birth-date"]/earliestDate/@type'
      record: 1941-O
    Geboorteplaats NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="birth-place"]/namePlaceSet/appellationValue[@xml:lang="nl"]'
      record: 1935-V
    Geboorteplaats FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="birth-place"]/namePlaceSet/appellationValue[@xml:lang="fr"]'
      record: 1935-V
    Geboorteplaats EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="birth-place"]/namePlaceSet/appellationValue[@xml:lang="en"]'
      record: 1935-V
    Geboorteplaats externe bron:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="birth-place"]/placeID[@source="TGN"]'
      record: 1935-V
    Sterftedatum begin:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalDatesActor[@type="death-date"]/earliestDate'
      record: 1874-C
    Sterftedatum eind:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalDatesActor[@type="death-date"]/latestDate'
      record: 1874-C
    Precisie sterftedatum:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalDatesActor[@type="death-date"]/earliestDate/@type'
      record: 1935-AV
    Sterfteplaats NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="death-place"]/namePlaceSet/appellationValue[@xml:lang="nl"]'
      record: 1935-V
    Sterfteplaats FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="death-place"]/namePlaceSet/appellationValue[@xml:lang="fr"]'
      record: 1935-V
    Sterfteplaats EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="death-place"]/namePlaceSet/appellationValue[@xml:lang="en"]'
      record: 1935-V
    Sterfteplaats externe bron:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/vitalPlaceActor[@type="death-place"]/placeID[@source="TGN"]'
      record: 1935-V
    Titel NL:
      xpath: '(descriptiveMetadata/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@pref="preferred" and @xml:lang="nl"])[1]'
      record: 1865-C
    Titel FR:
      xpath: '(descriptiveMetadata/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@pref="preferred" and @xml:lang="fr"])[1]'
      record: 1865-C
    Titel EN:
      xpath: '(descriptiveMetadata/objectIdentificationWrap/titleWrap/titleSet/appellationValue[@pref="preferred" and @xml:lang="en"])[1]'
      record: 1865-C
    School / stijl NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[@type="style"]/term[@xml:lang="nl"]'
      record: 1998-B-121
    School / stijl FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[@type="style"]/term[@xml:lang="fr"]'
      record: 1998-B-121
    School / stijl EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[@type="style"]/term[@xml:lang="en"]'
      record: 1998-B-121
    School / stijl externe bron:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[@type="style"]/conceptID[@source="AAT"]'
      record: 1998-B-121
    Datering begin:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/earliestDate'
      record: 1920-AN
    Datering eind:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/latestDate'
      record: 1955-B
    Precisie datering:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventDate/date/earliestDate/@type'
      record: 1955-B
    Periode NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[not(@type)]/term[@xml:lang="nl"]'
      record: 2005-AC
    Periode FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[not(@type)]/term[@xml:lang="fr"]'
      record: 2005-AC
    Periode EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/periodName[not(@type)]/term[@xml:lang="en"]'
      record: 2005-AC
    Beschrijving NL:
      xpath: 'descriptiveMetadata/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue[@xml:lang="nl"]'
      record: S-46
    Beschrijving FR:
      xpath: 'descriptiveMetadata/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue[@xml:lang="fr"]'
      record: S-46
    Beschrijving EN:
      xpath: 'descriptiveMetadata/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue[@xml:lang="en"]'
      record: S-46
    Objectcategorie NL:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="object-category"]/term[@pref="preferred" and @xml:lang="nl"]'
      record: 1999-AJ
    Objectcategorie FR:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="object-category"]/term[@pref="preferred" and @xml:lang="fr"]'
      record: 1999-AJ
    Objectcategorie EN:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="object-category"]/term[@pref="preferred" and @xml:lang="en"]'
      record: 1999-AJ
    Objectcategorie externe bron:
      xpath: 'descriptiveMetadata/objectClassificationWrap/classificationWrap/classification[@type="object-category"]/conceptID[@pref="preferred" and @source="AAT"]'
      record: 1999-AJ
    Objectnaam NL:
      xpath: 'descriptiveMetadata/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/term[@pref="preferred" and @xml:lang="nl"]'
      record: 1958-X-41
    Objectnaam FR:
      xpath: 'descriptiveMetadata/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/term[@pref="preferred" and @xml:lang="fr"]'
      record: 1958-X-41
    Objectnaam EN:
      xpath: 'descriptiveMetadata/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/term[@pref="preferred" and @xml:lang="en"]'
      record: 1958-X-41
    Objectnaam externe bron:
      xpath: 'descriptiveMetadata/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/conceptID[@pref="preferred" and @source="AAT"]'
      record: 1958-X-41
    Technische beschrijving NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/displayMaterialsTech'
      record: 1958-X-41
    Techniek NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="technique"]/term[@pref="preferred" and @xml:lang="nl"]'
      record: 1998-B-121
    Techniek FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="technique"]/term[@pref="preferred" and @xml:lang="fr"]'
      record: 1998-B-121
    Techniek EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="technique"]/term[@pref="preferred" and @xml:lang="en"]'
      record: 1998-B-121
    Techniek externe bron:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="technique"]/conceptID[@pref="preferred" and @source="AAT"]'
      record: 1998-B-121
    Materiaal NL:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="material"]/term[@pref="preferred" and @xml:lang="nl"]'
      record: 1958-X-7
    Materiaal FR:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="material"]/term[@pref="preferred" and @xml:lang="fr"]'
      record: 1958-X-7
    Materiaal EN:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="material"]/term[@pref="preferred" and @xml:lang="en"]'
      record: 1958-X-7
    Materiaal externe bron:
      xpath: 'descriptiveMetadata/eventWrap/eventSet/event[eventType/term="production"]/eventMaterialsTech/materialsTech/termMaterialsTech[@type="material"]/conceptID[@pref="preferred" and @source="AAT"]'
      record: 1958-X-7





  # Certificate Authority (also known as 'cacert') may not work on its own depending on your system and PHP configuration,
  # that's why a cacert.pem is included in this project (from https://curl.haxx.se/docs/caextract.html).
  # Set override_certificate_authority to 'true' when we need to specify our own cacert.pem (can be a relative path or an absolute system path).
  override_certificate_authority: true
  ssl_certificate_authority_file: 'cacert.pem'
